[workspace]
name = "kilted-libpython-bug"
authors = ["Erik Holum <eholum@gmail.com>"]
channels = ["conda-forge", "https://prefix.dev/robostack-kilted"]
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
cmake = ">=3.30,<4"
ninja = ">=1.13,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
python = ">=3.11,<3.13"
ros-kilted-ros-base = "*"
ros-kilted-tf2-eigen = "*"
lttng-ust = ">=2.13.9,<3"
mold = ">=2.40.4,<3"

[tasks]
# build = { cmd = "cmake -B build -G Ninja && cmake --build build" }
# run = { cmd = "./build/tf2_eigen_bug" }

build = { cmd = "colcon build" }
run = { cmd = "bash -c 'source install/setup.bash && tf2_eigen_bug'" }
clean = {cmd = "rm -r build install log"}

[activation.env]
# CXXFLAGS = "-fuse-ld=mold"
CMAKE_PREFIX_PATH = "${CONDA_PREFIX}"
LD_LIBRARY_PATH = "${CONDA_PREFIX}/lib"
LIBRARY_PATH = "${CONDA_PREFIX}/lib"
LDFLAGS = "-L${CONDA_PREFIX}/lib -Wl,-rpath,${CONDA_PREFIX}/lib"
